In [1]:
import numpy as np
arr=np.array([[1,2,3],[5,10,15]])
np.save("E://arr1.npy",arr)

In [3]:
getData=np.load("E://arr1.npy")
print(getData)

[[ 1  2  3]
 [ 5 10 15]]


In [11]:
# Creating an array
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Saving to a text file
np.savetxt("E:\\output.txt", data)

In [15]:
getTxtData=np.loadtxt("E:\\output.txt")
print(getTxtData)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [27]:
data2=np.array([[4, 5, 7],[8, 3, 1],[6, 4, 5]])
np.savetxt("E:\\saved.txt",data2,fmt='%d', delimiter=' ')

In [29]:
getTxtData=np.loadtxt("E:\\saved.txt")
print(getTxtData)

[[4. 5. 7.]
 [8. 3. 1.]
 [6. 4. 5.]]
